name: 构建JD Scripts镜像

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "docker/Dockerfile"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@master

      # 要去 https://hub.docker.com/ 那边注册一个账户然后配置用户名密码
      # - name: 构建并推送到Dockerhub官方镜像仓库
      #   uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     dockerfile: docker/Dockerfile
      #     repository: akyakya/jd_scripts
      #     tag_with_ref: true

      - name: 构建并推送到Github Packages
        uses: docker/build-push-action@v1
        if: env.GITHUB_TOKEN
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: docker/Dockerfile
          registry: docker.pkg.github.com
          repository: ${{ github.actor }}
          tag_with_ref: true
