# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: jd_updateFactoryTuanID

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16,17,18,20 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_updateFactoryTuanID
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【更新京喜工厂开团ID】'
        run: |
          node jd_jxFactoryCreateTuan.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
      #- name: '运行 【更新818互助码】'
        #run: |
          #node updateShareCode.js
       #env:
          #JD_COOKIE: ${{ secrets.JD_COOKIE }}
        
      - name: commit
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name lxk0301
          git add .
          git commit -m "update by lxk0301 Github Action" -a || echo "Nothing to update"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: master
