# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: qqyd1

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */11 * * *'
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 14.x

    steps:
    - uses: actions/checkout@v2
    - name: qqyd ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    -name: npm install
     run: |
       npm install
       npm install got #tough-cookie
   
    - name: ' 运行 【企鹅阅读】'
        run: |
          node qqyd.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}

